name: themoviedb_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter_pretty_dio_logger: ^3.0.0
  get_it: ^7.6.7
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.3.2
  intl: any
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  gap: ^3.0.1
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  injectable_generator: null
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true